### PR TITLE
Serialize/deserialize OOP

### PR DESCRIPTION
**Pull request by HugoGranstrom**
This was remarkably hard to get working as a nimib document. The order we define things matter so much and it might not always be the order that makes the most sense to explain something in. So this isn't directly my magnum opus... But it is written now at least. Feel free to read it and give feedback.

### CODE REVIEW

**Comment by pietroppeter** [comment]
This looks great! From a first quick read I have only one minor remark: we are motivating the OOP with our new target nimib, we probably could mention the fact that serialization/deserialization with JSON would also be an additional new requirement (that we did not have before).

And regarding out of order stuff I actually had an idea recently about a possible decent api to support out of order code, I should try to remember what it was 😀

**Comment by HugoGranstrom** [comment]
Thanks for the feedback, have added a sentence on why we need the JSON in nimib now :D 

Ohh, exciting :O 
It is more than just out-of-order code I struggled with here, though. For example, iteratively creating a parseHook to show the wrong behavior in the beginning. But once I have used one parseHook, it will be used for the rest of the code (I think). I had problem with that as well. So there are multiple hard parts about this specific problem :rofl

**Comment by pietroppeter** [comment]
looks good to me. the only thing left is to create html. nblog still has a basic publish mechanism where htmls are generated locally. :)

**Comment by HugoGranstrom** [comment]
Thanks! :D Now the htmls should be pushed

**Comment by pietroppeter** [comment]
Mmh why the part "the central part..." added in one of the commits has not made it to the deployed version? https://nimib.land/nblog/drafts/serialize_oop.html (checking from mobile)

**Comment by HugoGranstrom** [comment]
That's weird, I always preview using nimiBoost so it should always be the latest version in the HTML. Or I just did an edit without previewing it 😂

**Pull request merged**
